typography_spectrum: 0.2289
color:
  brandColors:
    - '#f3f8fe'
    - '#10130a'
    - '#b7d9fe'
    - '#9e9e9e'
    - '#6e6757'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.90363
analytics:
  google: null
  facebook: null
  twitter: null
name: KWbeta
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About us
    url: www.knowledgeworker.dk
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: KWBETA
description: Ite beta
purpose: []
