name: KWbeta
favicon: null
layout_spectrum: 0.48482
typography_spectrum: 0.2289
title: KWBETA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#45ab33'
    - '#ffffff'
    - '#60b751'
    - '#bce1b6'
    - '#80c574'
  brandStrength: 0.4375
  lightness: 0.8215327167417854
  saturation: 0.8366643523331732
  rhythmicContrast: 0.4197182927746326
purpose: []
