title: KWBETA
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8366643523331732
  brandStrength: 0.4375
  rhythmicContrast: 0.4197182927746326
  brandColors:
    - '#45ab33'
    - '#ffffff'
    - '#60b751'
    - '#bce1b6'
    - '#80c574'
  lightness: 0.8215327167417854
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: KWbeta
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2289
layout_spectrum: 1
